macOS: fix back button for nested nav pages and CI expansion
nblockchain/DotNetForms pull request #2
Opened 2021-05-04 17:42 UTC by aarani

2021-05-04 17:51 UTC, knocte commented
The CI commit message has the what but not the why.

2021-05-05 09:32 UTC, knocte requested changes

2021-05-05 09:32 UTC, knocte commented on DevopsNuget.config
> -    <add key="nuget" value="../s/Nuget" />
is this related to the PR?

2021-05-05 09:32 UTC, knocte commented on .github/workflows/main.yml
> +    - name: Upload packages
rename from 'Upload packages' to 'Upload packages as CI artifacts' to not confuse with nuget upload

2021-05-05 09:32 UTC, knocte commented on .github/workflows/main.yml
> +  build_and_pack:
why rename this?

2021-05-05 09:32 UTC, aarani commented on DevopsNuget.config
> -    <add key="nuget" value="../s/Nuget" />
yeah the build fails because that folder doesn't exist on our CI

2021-05-05 09:38 UTC, aarani commented on .github/workflows/main.yml
> +  build_and_pack:
should be reverted now

2021-05-05 09:56 UTC, knocte commented on DevopsNuget.config
> -    <add key="nuget" value="../s/Nuget" />
Say this in the commit message then.

2022-08-25 16:38 UTC, knocte commented
Superseded by https://github.com/nblockchain/DotNetForms/pull/3

2022-08-25 16:38 UTC, closed without merging